// DevFeed posts about Carlos's earlier projects, oldest first so the newest lands on top.
// Media lives in public/progress/past; `video` is the YouTube demo from his portfolio.
// Posts with neither media nor a video wait until Carlos sends a recording.
export const PAST_PROJECT_POSTS = [
  {"key": "past-netflix", "project": "NetflixDB", "title": "Netflix Database on Google Cloud", "body": "Built a Netflix-style relational database in MySQL and hosted it on a Google Cloud SQL instance. I pulled Kaggle CSV datasets into Cloud Storage buckets, loaded them through the GCloud Shell, then explored the catalog with Metabase dashboards and charts. My first real taste of cloud databases.", "tags": ["#MySQL", "#GoogleCloud", "#CloudSQL", "#Metabase", "#Kaggle"], "media": null, "video": "4tRYxzllkQA"},
  {"key": "past-pet-adoption", "project": "PetAdoption", "title": "PetHome: a pet adoption center site", "body": "Class project for MAC 110 (Project Management). Before writing any code I planned the whole thing the SDLC way: Work Breakdown Structure, SWOT analysis, Context and Data Flow Diagrams, a Decision Table and a Gantt chart. Then I built PetHome: pages for Home, About, Adopt, Foster and Volunteer with featured pets, a newsletter signup and adoption, foster and volunteer forms backed by PHP handlers that validate and sanitize the input.", "tags": ["#HTML", "#CSS", "#JavaScript", "#PHP", "#SDLC", "#ProjectManagement"], "media": "pet-adoption.gif", "video": "PmNVaZcAHDA"},
  {"key": "past-hangman", "project": "HangMan", "title": "HangMan in the terminal (C++)", "body": "The classic word game in a C++ console. A random word is picked from a built-in list, and every wrong letter adds a body part to the ASCII gallows. Six misses and it's over. I split it into two classes: Game tracks the word, the revealed letters and the misses, while Message draws everything, from the title screen and gallows to the YOU WIN banner. Input is validated, so only new letters count.", "tags": ["#CPlusPlus", "#OOP", "#ASCIIArt", "#ConsoleGame"], "media": "hangman.gif", "video": null},
  {"key": "past-gpa-calc", "project": "GPACalc", "title": "College GPA Calculator (C++)", "body": "A C++ console tool that asks how many classes you took, then each class's name, credits and grade, and returns your weighted GPA rounded to two decimals. Every number is validated: no negative credits, no grades outside 0.0 to 4.0, and bad input gets asked again instead of crashing.", "tags": ["#CPlusPlus", "#Structs", "#Vectors", "#InputValidation"], "media": "gpa-calculator.gif", "video": "jCxr4QT_Mm4"},
  {"key": "past-library", "project": "LibraryMgmt", "title": "Library Management System (Java)", "body": "A command-line library for books, vinyl records and movies. You can show the catalog, borrow, return and donate items. Book, Vinyl and Movie all extend one LibraryItem class, so the borrow and return logic is written once and works for every kind of item, and donations add new titles on the fly.", "tags": ["#Java", "#OOP", "#Inheritance", "#ArrayList", "#DataStructures"], "media": "library-management.gif", "video": "6lAlVk0Kl3I"},
  {"key": "past-dmv", "project": "DMVProject", "title": "DMV vehicle registration (Java)", "body": "A Java app that simulates registering cars at the DMV. It takes the owner's name and address, then as many vehicles as you want (make, model, VIN, plate and year), and prints the full owner record at the end. Owner keeps an ArrayList of Vehicle objects, and each class formats its own details with toString().", "tags": ["#Java", "#OOP", "#ArrayList", "#Scanner", "#DataStructures"], "media": "dmv-project.gif", "video": "817uSUc2tYg"},
  {"key": "past-employee", "project": "EmployeeMgmt", "title": "Employee Management System (C++)", "body": "My Advanced C++ final: a menu-driven system to add, update, delete and list employee records, saved to and loaded from employees.txt so the data survives a restart. Manager inherits from Employee with a polymorphic displayDetails(), custom InvalidInputException and FileIOException classes catch bad input and file errors, and std::thread demos run adds and updates at the same time.", "tags": ["#CPlusPlus", "#OOP", "#Polymorphism", "#Multithreading", "#FileIO"], "media": "employee-management.gif", "video": "kEqftDn_TNY"},
  {"key": "past-gunbound", "project": "Gunbound2D", "title": "Gunbound 2D replica in Unity", "body": "A two-player artillery game inspired by Gunbound, built in Unity in 3 days for my Game Programming final. Players take turns on a 20-second timer: move with A and D, hold Space to charge the power bar, and release to fire. Shots fly with Rigidbody2D physics and gravity, spin through the air and knock health off the other player's bar. Eleven C# scripts split up the players, shots, power bar, health and the turn logic.", "tags": ["#Unity", "#CSharp", "#GameDev", "#Physics2D", "#TurnBased"], "media": null, "video": "75j3qdD0zp4"},
  {"key": "past-flappy", "project": "FlappyBird", "title": "Flappy Bird replica in Unity", "body": "A Flappy Bird remake for MAC 280 (Videogame Programming). Three small C# scripts run the game: BirdScript flaps the bird with a Rigidbody2D whenever you hit Space, PipeSpawnerScript spawns a new pipe every 2 seconds at a random height, and PipeScript slides the pipes left and deletes them once they're off screen.", "tags": ["#Unity", "#CSharp", "#GameDev", "#Rigidbody2D"], "media": null, "video": "H0MAK-MvcbE"},
  {"key": "past-win98-v1", "project": "Win98Blog v1", "title": "Win98 Blog v1: where it started", "body": "The very first version of this site. I started from an open-source Windows 95 portfolio template built in React and Vite (by yuteoctober) and filled it with my own bio, resume and projects. It was my first time working in a big React codebase, and everything you see here today grew out of it.", "tags": ["#React", "#Vite", "#JavaScript", "#RetroUI"], "media": "win98blog-v1.gif", "video": null},
  {"key": "past-warm-rain", "project": "WarmRain", "title": "Warm Rain of Summer: the 51-page design doc", "body": "My Unreal Engine 5 game, built alongside Epic's official UE5 course. A young man tired of his routine leaves it all behind, takes over his uncle's countryside farm and travels across South America by bike and an old van, with a rescued cat and a stray dog who join him on the road. The 51-page Game Design Document covers the three pillars (Exploration, Movement, Story), quests, a Polaroid album you decorate with your photos, camping nights, pet customization, the world, characters, levels and UI.", "tags": ["#UnrealEngine5", "#GameDesign", "#GDD", "#Blueprints", "#Storytelling"], "media": "warm-rain-gdd.gif", "video": null},
  {"key": "past-portfolio", "project": "MyPortfolio", "title": "My portfolio, hand-built", "body": "My portfolio at carlosz98.github.io/MyPortFolio, written in plain HTML, CSS and JavaScript with no framework and no build step. Under the warm editorial look there's a skills constellation drawn on canvas, a light/dark theme that remembers your choice, a retro terminal you open with the / key, a typing robot guide, project filters, scroll reveals, a custom cursor and a live 'last commit' badge from the GitHub API.", "tags": ["#HTML", "#CSS", "#JavaScript", "#Canvas", "#GitHubPages"], "media": "my-portfolio.gif", "video": null},
  {"key": "past-win98blog", "project": "Win98Blog", "title": "Win98Blog: the site you're on", "body": "Version three, and the one you're using right now: a Windows 98 desktop in the browser, built with React and Vite. It has a BIOS boot screen, draggable windows, a Start menu and taskbar, and 30 desktop icons, including this DevFeed and the Scrapbook (Firebase, and only I can post), Winamp, CarlosBot on MSN, Paint, Minesweeper, Doom, a 3D magazine, a visitor map and a guestbook.", "tags": ["#React", "#Vite", "#Firebase", "#FramerMotion", "#RetroUI"], "media": "win98blog-tour.gif", "video": "ZP-KHYRXtqI"},
  {"key": "past-retrohub", "project": "RetroHub", "title": "RetroHub: a social app for retro gamers", "body": "RetroHub started as my Android class final and grew into a full social platform for retro gaming fans, built in Kotlin and Jetpack Compose on Firebase. It has a community feed, real-time DMs and group chats, a game database powered by IGDB with YouTube trailers, Twitch and YouTube streams, a magazine reader with reading progress, shelves and reviews, soundtrack albums, and profiles with XP levels, an activity heatmap and a gaming-personality radar chart, all in a comic scrapbook style.", "tags": ["#Android", "#Kotlin", "#JetpackCompose", "#Firebase", "#MVVM"], "media": null, "video": "AdAOmZPQE8Q"},
];
